#ifndef RDF4CPP_BLANKNODEIDMANAGEMENT_METALL_COMMON_HPP
#define RDF4CPP_BLANKNODEIDMANAGEMENT_METALL_COMMON_HPP

#include <rdf4cpp/rdf.hpp>



#endif  //RDF4CPP_BLANKNODEIDMANAGEMENT_METALL_COMMON_HPP
