name: Detect POBR diff

on: [ pull_request ]

concurrency:
  group: detect-pobr-diff-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect-pobr-diff:
    uses: dice-group/cpp-conan-release-reusable-workflow/.github/workflows/abi-diff.yml@v2.1.1
    with:
      os: ubuntu-24.04
      cc: clang-20
      base-branch: ${{ github.base_ref }}
      setup_tools: true
      search-path: >
        src/rdf4cpp/storage/identifier
        src/rdf4cpp/storage/view
        src/rdf4cpp/storage/reference_node_storage/detail/BiDirFlatMap.hpp
        src/rdf4cpp/storage/reference_node_storage/detail/ConstString.hpp
        src/rdf4cpp/storage/reference_node_storage/detail/IndexFreeList.hpp
      abi-version-header: src/rdf4cpp/version.hpp
      abi-version-const: rdf4cpp::pobr_version
    secrets:
      CONAN_CICD_USERNAME: ${{ secrets.CONAN_CICD_USERNAME }}
      CONAN_CICD_PASSWORD: ${{ secrets.CONAN_CICD_PASSWORD }}
      CONAN_CICD_ENDPOINT: ${{ secrets.CONAN_CICD_ENDPOINT }}
