name: Publish Release
on:
  create:

concurrency:
  group: publish-release-${{ github.workflow }}-${{ github.ref }}

jobs:
  publish-conan-branch-package:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    uses: dice-group/cpp-conan-release-reusable-workflow/.github/workflows/publish-release.yml@v2.1.1
    with:
      public_artifactory: true
      os: ubuntu-24.04
      compiler: clang-21
      use-tag: true
      conan-options: -o boost/*:header_only=True
    secrets:
      CONAN_CICD_USERNAME: ${{ secrets.CONAN_CICD_USERNAME }}
      CONAN_CICD_PASSWORD: ${{ secrets.CONAN_CICD_PASSWORD }}
      CONAN_CICD_ENDPOINT: ${{ secrets.CONAN_CICD_ENDPOINT }}
