name: Run unit tests and examples
on: [ 'pull_request' ]


jobs:
  tests_and_example_matrix:
    strategy:
      matrix:
        config:
          - os: ubuntu-24.04
            compiler: gcc-14
      fail-fast: false
    name: ${{ matrix.config.compiler }}, ${{ matrix.config.os }}
    uses: ./.github/workflows/reusable_run_test_and_examples_by_linking_type.yml
    with:
      os: ${{ matrix.config.os }}
      compiler: ${{ matrix.config.compiler }}
      cmake-version: 4.4.0
      conan-version: 2.32.0
      with-coverage: true
      with-sanitizer: false
      build-shared-libs: true
    secrets:
      coverall-token: ${{ secrets.COVERALLS_TOKEN }}
